"""Схема v1: календарная часть

Девять таблиц первого релиза - календарь без курсов (ADR-019 с поправкой
ADR-020). Курсовые таблицы из `SPEC.md` §9 здесь отсутствуют намеренно:
их поля выводятся из манифеста курса, которого ещё нет.

Файл сгенерирован autogenerate и оставлен близким к оригиналу: расхождение
с моделями ловится `alembic check`, и чем меньше ручной правки, тем меньше
поводов ему сработать. Смысл каждой таблицы - в докстрингах моделей
(`jarvis_api/db/models.py`), дублировать его здесь незачем.

Revision ID: be67a3dd2486
Revises:
Create Date: 2026-09-05 17:52:04.741325+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "be67a3dd2486"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Проба бэкапа с Э1 своё отслужила: она показывала, что после pg_restore
    # вернулись данные, а не только схема, - пока настоящих таблиц не было.
    # Удаляется здесь по решению owner (docs/BUILD-PROGRESS.md, Э1). Без этого
    # она осталась бы в prod-базе навсегда и всплывала бы в каждом
    # `alembic check` как лишняя таблица.
    op.execute("DROP TABLE IF EXISTS restore_probe")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=256), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "status in ('ok', 'error', 'degraded')", name=op.f("ck_audit_log_status_known")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_at", "audit_log", ["at"], unique=False)
    op.create_index("ix_audit_log_kind_at", "audit_log", ["kind", "at"], unique=False)
    op.create_table(
        "calendar_events",
        sa.Column("external_key", sa.String(length=256), nullable=False),
        sa.Column("calendar", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location", sa.String(length=256), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("google_event_id", sa.String(length=256), nullable=True),
        sa.Column(
            "sync_state", sa.String(length=64), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "calendar in ('itmo', 'study', 'events')",
            name=op.f("ck_calendar_events_calendar_known"),
        ),
        sa.CheckConstraint(
            "source in ('itmo', 'capture')", name=op.f("ck_calendar_events_source_known")
        ),
        sa.CheckConstraint(
            "sync_state in ('pending', 'synced', 'failed')",
            name=op.f("ck_calendar_events_sync_state_known"),
        ),
        sa.PrimaryKeyConstraint("external_key", name=op.f("pk_calendar_events")),
        sa.UniqueConstraint("google_event_id", name=op.f("uq_calendar_events_google_event_id")),
    )
    op.create_index("ix_calendar_events_starts_at", "calendar_events", ["starts_at"], unique=False)
    op.create_index(
        "ix_calendar_events_sync_state", "calendar_events", ["sync_state"], unique=False
    )
    op.create_table(
        "capture_drafts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("modality", sa.String(length=64), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=True),
        sa.Column("extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("confirmed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "modality in ('text', 'image', 'audio')", name=op.f("ck_capture_drafts_modality_known")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capture_drafts")),
    )
    op.create_index("ix_capture_drafts_created_at", "capture_drafts", ["created_at"], unique=False)
    op.create_table(
        "day_flags",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("note", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ends_on >= starts_on", name=op.f("ck_day_flags_range_ordered")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_day_flags")),
    )
    op.create_index(op.f("ix_day_flags_starts_on"), "day_flags", ["starts_on"], unique=False)
    op.create_index(
        "uq_day_flags_late_classes_day",
        "day_flags",
        ["starts_on"],
        unique=True,
        postgresql_where=sa.text("reason = 'late_classes'"),
    )
    op.create_table(
        "integration_tokens",
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("value_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind in ('password', 'refresh_token', 'access_token')",
            name=op.f("ck_integration_tokens_kind_known"),
        ),
        sa.PrimaryKeyConstraint("provider", "kind", name=op.f("pk_integration_tokens")),
    )
    op.create_table(
        "itmo_lessons",
        sa.Column("source_key", sa.String(length=256), nullable=False),
        sa.Column("lesson_date", sa.Date(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subject", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=True),
        sa.Column("teacher", sa.String(length=256), nullable=True),
        sa.Column("room", sa.String(length=256), nullable=True),
        sa.Column("building", sa.String(length=256), nullable=True),
        sa.Column("mode", sa.String(length=64), nullable=True),
        sa.Column("online_url", sa.String(length=2048), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("source_key", name=op.f("pk_itmo_lessons")),
    )
    op.create_index(
        op.f("ix_itmo_lessons_lesson_date"), "itmo_lessons", ["lesson_date"], unique=False
    )
    op.create_index("ix_itmo_lessons_starts_at", "itmo_lessons", ["starts_at"], unique=False)
    op.create_table(
        "job_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job", sa.String(length=64), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status", sa.String(length=64), server_default=sa.text("'running'"), nullable=False
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status in ('running', 'ok', 'failed')", name=op.f("ck_job_runs_status_known")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
        sa.UniqueConstraint("job", "run_date", name="uq_job_runs_job_run_date"),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column(
            "timezone",
            sa.String(length=64),
            server_default=sa.text("'Europe/Moscow'"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_settings_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
    )
    op.create_table(
        "capture_blobs",
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["capture_drafts.id"],
            name=op.f("fk_capture_blobs_draft_id_capture_drafts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("draft_id", name=op.f("pk_capture_blobs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Проба Э1 назад не создаётся: откат возвращает базу к отсутствию схемы
    # приложения, а не к состоянию конкретного дня прошлого этапа.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("capture_blobs")
    op.drop_table("settings")
    op.drop_table("job_runs")
    op.drop_index("ix_itmo_lessons_starts_at", table_name="itmo_lessons")
    op.drop_index(op.f("ix_itmo_lessons_lesson_date"), table_name="itmo_lessons")
    op.drop_table("itmo_lessons")
    op.drop_table("integration_tokens")
    op.drop_index(
        "uq_day_flags_late_classes_day",
        table_name="day_flags",
        postgresql_where=sa.text("reason = 'late_classes'"),
    )
    op.drop_index(op.f("ix_day_flags_starts_on"), table_name="day_flags")
    op.drop_table("day_flags")
    op.drop_index("ix_capture_drafts_created_at", table_name="capture_drafts")
    op.drop_table("capture_drafts")
    op.drop_index("ix_calendar_events_sync_state", table_name="calendar_events")
    op.drop_index("ix_calendar_events_starts_at", table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_index("ix_audit_log_kind_at", table_name="audit_log")
    op.drop_index("ix_audit_log_at", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
