/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Сетка календаря на день или неделю
         * @description Пары университета, личные события, пометки дней и пометка давности.
         *
         *     Границы периода считает сервер, а не клиент: неделя зависит от
         *     `settings.timezone`, которой у клиента нет (инвариант 1). Запрос за
         *     пределы окна забора - не ошибка, а законный вопрос: дни приходят
         *     с `mirror_covers = false`, то есть «сохранённых данных нет».
         */
        get: operations["\u0441\u0435\u0442\u043A\u0430_\u043A\u0430\u043B\u0435\u043D\u0434\u0430\u0440\u044F_api_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/day-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Периоды исключений за интервал
         * @description Периоды, **пересекающие** интервал, а не лежащие внутри него.
         *
         *     Умолчание - окно забора расписания (`sync_window`), а не «все периоды»:
         *     экран открывается на текущей неделе, и период из позапрошлого семестра
         *     ему не нужен. Параметры называются `from` и `to`, потому что `from` -
         *     ключевое слово Python: имя в контракте задаётся `alias`, иначе клиент
         *     получил бы `начало` транслитом или второе имя поля.
         */
        get: operations["\u0441\u043F\u0438\u0441\u043E\u043A_\u043F\u0435\u0440\u0438\u043E\u0434\u043E\u0432_api_day_flags_get"];
        put?: never;
        /**
         * Внести период исключений
         * @description Создать период.
         *
         *     Законны и дают 201: период в один день, перекрытие с уже внесённым,
         *     период задним числом. §2.5 требует по ним **пересчёта отставания**,
         *     а не запрета: «я болел позапрошлую неделю» вносится именно так.
         *
         *     Коммит явный: период и строка аудита обязаны уехать одной транзакцией,
         *     а `session_scope` границу транзакции не ставит.
         */
        post: operations["\u0432\u043D\u0435\u0441\u0442\u0438_\u043F\u0435\u0440\u0438\u043E\u0434_api_day_flags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/day-flags/{flag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Убрать период исключений
         * @description Удалить период owner. Системную пометку удалить нельзя.
         *
         *     Отказ на `late_classes` - 409, а не 403: дело не в правах, а в том, что
         *     снятая руками пометка вернулась бы сама следующим прогоном джоба (§4).
         *     Обещать owner результат, который не сохранится, - та же ложь, что
         *     правдоподобная выдумка на экране (инвариант 9).
         *
         *     Имя параметра латиницей не только ради контракта: Starlette разбирает
         *     шаблон пути ASCII-регуляркой, и `{id_периода}` не распознаётся как
         *     параметр вовсе - маршрут превращается в литерал, а любой `DELETE`
         *     отвечает 404 «Not Found». Найдено тестом, не ревью.
         */
        delete: operations["\u0443\u0431\u0440\u0430\u0442\u044C_\u043F\u0435\u0440\u0438\u043E\u0434_api_day_flags__flag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Живость процесса.
         *
         *     Базу не трогает намеренно: эндпоинт должен отвечать и при пустом
         *     DATABASE_URL - им проверяется, что контейнер поднялся, отдельно от того,
         *     доступна ли база.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CalendarOut
         * @description Сетка календаря на период: ответ `GET /api/calendar`.
         */
        CalendarOut: {
            /**
             * Days
             * @description Один элемент на день периода, по порядку
             */
            days: components["schemas"]["DayOut"][];
            freshness: components["schemas"]["FreshnessOut"];
            period: components["schemas"]["PeriodOut"];
            /**
             * Timezone
             * @description Зона owner из settings, в которой приведены моменты
             */
            timezone: string;
        };
        /**
         * DayFlagIn
         * @description Тело `POST /api/day-flags`.
         *
         *     Проверки живут здесь, а не в базе: словарь причин будет меняться, а CHECK
         *     ради нового слова ничего не защищает. В базе остаются два ограничения,
         *     которые пережить нельзя, - порядок дат и уникальность автопометки на день.
         */
        DayFlagIn: {
            /**
             * Ends On
             * Format: date
             */
            ends_on: string;
            /** Note */
            note?: string | null;
            /** Reason */
            reason: string;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
        };
        /**
         * DayFlagOut
         * @description Период исключений, попавший на этот день (§2.5).
         */
        DayFlagOut: {
            /**
             * Ends On
             * Format: date
             * @description Включительно: период «с 1 по 7» содержит седьмое
             */
            ends_on: string;
            /** Id */
            id: number;
            /**
             * Manual
             * @description Внесён owner, а не проставлен системой
             */
            manual: boolean;
            /** Note */
            note?: string | null;
            /**
             * Reason
             * @description Свободное слово owner либо late_classes от системы
             */
            reason: string;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
        };
        /**
         * DayFlagsOut
         * @description Ответ `GET /api/day-flags`.
         *
         *     Объектом, а не голым массивом: массив на верхнем уровне нельзя расширить
         *     ни одним полем, не сломав клиента, - а список периодов рано или поздно
         *     захочет отдавать границы запрошенного интервала.
         */
        DayFlagsOut: {
            /** Flags */
            flags: components["schemas"]["DayFlagOut"][];
        };
        /**
         * DayOut
         * @description День сетки.
         *
         *     `mirror_covers` отвечает на вопрос, который иначе неотличим от пустоты:
         *     пустой день внутри окна забора - «ничего не запланировано», а день,
         *     до которого забор не доходил, - «сохранённых данных нет». Схлопнуть их
         *     в один пустой массив значило бы соврать (инвариант 9).
         */
        DayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Events */
            events: components["schemas"]["EventOut"][];
            /** Flags */
            flags: components["schemas"]["DayFlagOut"][];
            /** Is Today */
            is_today: boolean;
            /**
             * Mirror Covers
             * @description День попадает в окно последнего успешного забора
             */
            mirror_covers: boolean;
        };
        /**
         * ErrorBody
         * @description Тело любого отказа API.
         *
         *     Имя класса латиницей, в отличие от остального кода проекта, и это не
         *     вкусовщина: имена моделей Pydantic попадают в контракт именами схем
         *     OpenAPI, а из них генератор делает имена типов TypeScript. Кириллица
         *     там формально законна и практически ломает автодополнение и генераторы.
         *     То же правило действует в `api/schemas.py`.
         */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: string[] | null;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * EventOut
         * @description Блок сетки: пара университета или личное событие.
         *
         *     Поля разных источников не сливаются в одно: у пары есть вид занятия
         *     и аудитория, у личного события - место и заметка. Пустое поле приходит
         *     как `null`, а не пропадает (`exclude_none` не используется): клиент
         *     обязан различать «поля нет в этом виде события» и «поле не заполнено».
         *
         *     Значения `source` - два: `itmo` и `event`. Занятий курсов (`study`)
         *     в календарном релизе нет: их время считается по манифесту курса (§4),
         *     который уехал в дорожку курсов вместе с ADR-027 п.11.
         */
        EventOut: {
            /** Building */
            building?: string | null;
            /**
             * Conflict
             * @description Пересекается по времени с другим событием периода
             */
            conflict: boolean;
            /** Description */
            description?: string | null;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /**
             * Key
             * @description Стабильный ключ источника: source_key пары или external_key
             */
            key: string;
            /**
             * Lesson Kind
             * @description Вид занятия: лекция, практика
             */
            lesson_kind?: string | null;
            /**
             * Location
             * @description Место личного события
             */
            location?: string | null;
            /**
             * Mode
             * @description Формат портала: Очный, Дистанционный
             */
            mode?: string | null;
            /** Online Url */
            online_url?: string | null;
            /** Room */
            room?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "itmo" | "event";
            /**
             * Starts At
             * Format: date-time
             * @description Начало, приведённое к зоне owner
             */
            starts_at: string;
            /** Teacher */
            teacher?: string | null;
            /** Title */
            title: string;
        };
        /**
         * FreshnessOut
         * @description Свежесть расписания (§10).
         *
         *     Полосу давности показывает `state`; `portal` только объясняет причину.
         *     Фразу собирает клиент: макет печатает один и тот же момент двумя
         *     форматами - «от 12 октября, 07:10» в полосе и «от 12.10» на блоке пары.
         */
        FreshnessOut: {
            /**
             * Covered From
             * @description Окно вокруг даты забора, включительно
             */
            covered_from: string | null;
            /** Covered To */
            covered_to: string | null;
            /**
             * Fetched At
             * @description Последний успешный ответ портала
             */
            fetched_at: string | null;
            /**
             * Portal
             * @description unknown - прогонов забора в журнале нет
             * @enum {string}
             */
            portal: "ok" | "failing" | "unknown";
            /**
             * State
             * @description never - забор ещё не проходил ни разу
             * @enum {string}
             */
            state: "fresh" | "stale" | "never";
        };
        /**
         * Health
         * @description Ответ /health. Время отдаётся, чтобы инвариант 7 был проверяем извне.
         */
        Health: {
            /** Env */
            env: string;
            /** Status */
            status: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Version */
            version: string;
        };
        /** PeriodOut */
        PeriodOut: {
            /**
             * Ends On
             * Format: date
             * @description Включительно
             */
            ends_on: string;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
            /**
             * Today
             * Format: date
             * @description Сегодня в зоне owner, независимо от периода
             */
            today: string;
            /**
             * View
             * @enum {string}
             */
            view: "day" | "week";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "\u0441\u0435\u0442\u043A\u0430_\u043A\u0430\u043B\u0435\u043D\u0434\u0430\u0440\u044F_api_calendar_get": {
        parameters: {
            query?: {
                /** @description Масштаб: день или неделя */
                view?: "day" | "week";
                /** @description Любая дата внутри периода. Не задана - сегодня в зоне owner */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOut"];
                };
            };
            /** @description Нет действующего токена Cloudflare Access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Токен принадлежит не owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Запрос не разобран */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description База данных или настройки недоступны */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    "\u0441\u043F\u0438\u0441\u043E\u043A_\u043F\u0435\u0440\u0438\u043E\u0434\u043E\u0432_api_day_flags_get": {
        parameters: {
            query?: {
                /** @description Не задано - начало окна забора расписания */
                from?: string | null;
                /** @description Включительно. Не задано - конец окна забора */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayFlagsOut"];
                };
            };
            /** @description Нет действующего токена Cloudflare Access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Токен принадлежит не owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Запрос не разобран */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description База данных или настройки недоступны */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    "\u0432\u043D\u0435\u0441\u0442\u0438_\u043F\u0435\u0440\u0438\u043E\u0434_api_day_flags_post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayFlagIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayFlagOut"];
                };
            };
            /** @description Нет действующего токена Cloudflare Access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Токен принадлежит не owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Ограничение базы или системная пометка */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Запрос не разобран */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description База данных или настройки недоступны */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    "\u0443\u0431\u0440\u0430\u0442\u044C_\u043F\u0435\u0440\u0438\u043E\u0434_api_day_flags__flag_id__delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет действующего токена Cloudflare Access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Токен принадлежит не owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Периода с таким id нет */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Ограничение базы или системная пометка */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Запрос не разобран */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description База данных или настройки недоступны */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
